# Options for rendering all notebooks in Codigo/notebooks folder.

# PROJECT INFORMATION
project:
  # NAME OF PROJECT
  title: "notebooks"
  # OUTPUT DIRECTORY FOR RENDERED FILES
  output-dir: rendered

# OUTPUT FORMATS
format: 
  # HTML
  #html:
    #theme: cerulean
    #toc: true
    #toc-depth: 4
    #number-sections: true
  # PDF
  pdf:
    toc: true
    toc-depth: 4
    number-sections: true

# KNITR OPTIONS
knitr:
  opts_chunk:
    fig.path: figures

# AUTHOR INFORMATION
author:
  name: "Álvaro Román Gómez"
  email: "roman.gomez.alvaro@gmail.com"
  url: "https://github.com/Alvaro-R"
  github: "Alvaro-R"

# DATE INFORMATION
date: last-modified

# BIBLIOGRAPHY
bibliography: ../../Memoria/bib/reference.bib
biblio-style: apalike
link-citations: yes

# EXECUTION INFORMATION
execute: 
  cache: true
  echo: true
  include: true
  warning: false
  error: false
  message: false
  
# CODE OPTIONS
code-overflow: wrap
