repos:

#TEST BLACK FORMATING
- repo: https://github.com/ambv/black
  rev: 23.1.0
  hooks:
  - id: black
    #CONFIGURE BLACK ARGUMENTS
    args:
      - --line-length=88
    # language should be local
    language_version: python3.11.2
    stages: [commit]

#TEST FLAKE8 FORMATING
- repo: https://github.com/pycqa/flake8
  rev: 3.7.9
  hooks:
  - id: flake8
    #CONFIGURE FLAKE8 ARGUMENTS    
    args:
      - "--max-line-length=88"
      #EXCLUDED DIRECTORIES
      - "--exclude=build,dist,*__init__.py"
      #IGNORE ERRORS TO AVOID CONFLICTS WITH BLACK
      # E203: whitespace before.
      # W503: line break before binary operator
      #E266: too many leading '#' for block comment
      #E501: line too long
      #F403: 'from module import *' used; unable to detect undefined names
      #F401: 'module' imported but unused
      - "--ignore=E203,W503"
      - "--max-complexity=18"
      - "--select=B,C,E,F,W,T4,B9"
    stages: [commit]

#TEST PYDOCSTYLE FORMATING
- repo: https://github.com/PyCQA/pydocstyle
  rev: 4.0.1
  hooks:
  - id: pydocstyle
    args:
      # D100 Missing docstring in public module
      # D104 Missing docstring in public package
      # D107 Missing docstring in __init__
      # D203 1 blank line required before class docstring (found 0)
      # D213 Multi-line docstring summary should start at the second line
      # D406 Section name should end with a newline ('Attributes', not 'Attributes:')
      # D407 Missing dashed underline after section ('Attributes')
      # D413 Missing blank line after last section ('Returns')
      # D416 Section name should end with a semicolon ('Parameters:', not 'Parameters')
      - "--ignore=D100,D104,D107,D203,D212,D406,D407,D413,D416"
      - "--match=.*\\.py"
    stages: [commit]

#MYPY TYPE CHECKING
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.1.1
  hooks:
  - id: mypy